### ISSUE TITLE
Scaling seems does not work.

### ISSUE THREAD

**Issue by n1n9-jp** [giniedp/spritespin#42]
Hi!
I have used the images with 3040px x 3040px in the div which are 'width: 30%'.
I have used the "sizeMode: 'fit'" or 'stretch' or 'fill', it seems does not work.
What am I wrong with it?
Thanks.

**Comment by giniedp** [comment]
transparent background is problematic for spritespin, because it tries to detect whether a browser would downsample (resize) an image or not. Without a background color spritespin can not do that. You should set the following option `detectSubsampling: false`

Please also consider resizing your images. They are way too huge. A single file is 12MB in file size. I have to download 120MB for a single spritespin preview. Target a reasonable resolution of about 600x600 pixels

**Comment by n1n9-jp** [comment]
Thank you so much.
I have just added `detectSubsampling: false` and it is fine(no need to background color).
