### ISSUE TITLE
the plugin keeps creating undefined frames and how do I set each image to its natural size?

### ISSUE THREAD

**Issue by catalin560** [giniedp/spritespin#60]
so these are my options:
```
                    $(el).spritespin({
                        source: sprArr,
                        loop: false,
                        sizeMode: 'fit',
                        renderer: 'image',
                        animate: false,
                        frames: sprArr.length,
                        plugins: [
                        '360',
                        'move'
                        ],
                        responsive: true
                    });
                });
```
where `el` is the container of my imgs and `sprArr` is where I push those img's srcs.
now to fix the issue with undefined frames I just forced it to use the exact number of imgs that are in my `sprArr` and it seems to have worked.
But I can't figure out how to display my imgs in their natural size... they all seem to stretch out no matter what values I pass to: `sizeMode` or `responsive`
I gave the container a width in % but it seems to ignore that and it calculates its own width.
So when `sizeMode: 'fit'` they seem to stretch at the size of the biggest img,
when `sizeMode: 'original'` they stretch at the size of the smallest img and
when `responsive: false` they stretch to an even smaller size?!

**Comment by giniedp** [comment]
When using the `360` plugin, you have to tell spritespin how many frames you are going to use per 360 rotation (`frames` option) and how many viewing angles you have (`lanes` option). If you dont, spritespin will try to guess these values but that only works in rare cases. I doubt that you actually need the `360` plugin, since you don't have  the `lanes` option set. Now remove the `360` plugin from your setup. Then if `frames` is not set, it will fallback to `source.length`.

If `width` and `height` is not set (as in your example), spritespin will use the `width` and `height` of the first image and use that as the size of the container. All images should have the same size or the same aspect ratio. Otherwise they will be stretched into the size of the container (size of first image). You can use the `sizeMode` to avoid stretching:

sizeMode: 'original' will not stretch the image and place it horizontally and vertically centered using the original image dimensions.
sizeMode: 'fit' will scale the image so it fits into the container without cutting the image off.
sizeMode: 'fill' will scale the image so it fills the whole container. The image might get cut off.

**Comment by catalin560** [comment]
thanks! I think I got it... also happy new year!
you may close this thread
