### ISSUE TITLE
Not loading on iPhone 5

### ISSUE THREAD

**Issue by foxted** [giniedp/spritespin#8]
I have a little problem and I can't figure out what's going on. Everything works well on desktop but when I try to load the page on an iPhone, the plugin is not loading.

Here is the error I got : 

IndexSizeError: DOM Exception 1: Index or size was negative, or greater than the allowed value.

Here is the link : 

http://dev.nwseatcovers.com/en/seat-covers/oe-series/original-equipment

Anyone got an idea ??

Thanks!

**Comment by Timak304** [comment]
The problem is the function `naturalSize` that gets 0 for width and height values. So the call of `data.context.drawImage(data.images[0], x, y, data.frameWidth, data.frameHeight, 0, 0, data.width, data.height);` give wrong values, which causes the exception.
You can solve the problem using naturalWidth as fallback in the function `naturalSize`:
`return { width: image.naturalWidth || img.width, height: image.naturalHeight || img.height };`

**Comment by giniedp** [comment]
thank you i add that fix to the next push.
