### ISSUE TITLE
'spritespin' is not exported from 'spritespin' (imported as 'SpriteSpin').

### ISSUE THREAD

**Issue by NhatNamVo** [giniedp/spritespin#82]
I imported SpriteSpin into module View360. When SpriteSpin.spritespin() is called. 'spritespin' is not exported from 'spritespin' (imported as 'SpriteSpin') display. Is there a way render without spritespin() function ? Thank you

```
import * as SpriteSpin from "spritespin"
const View360 = ()=> {
      const $= document.querySelector.bind(document);
      const option = {
      source: SpriteSpin.sourceArray("/images/HRV/Black/HRV-{frame}.jpg", { frame: [1, 35], digits: 1 }),
      animate: false,
      detectSubsampling: false,
      sense: 2,
      frames: 35,
      responsive: true,
      target: view,
      sizeMode: 'fill',
      width: 16,
      height: 9,
      }
      SpriteSpin.spritespin($('#spritespin'),option);
}
```

**Comment by giniedp** [comment]
Hi
i just answered that question on Disquss. Here is the excerpt

The current release of SpriteSpin (version 4) does not have the **spritespin** function exported. Further it depends on jQuery. Importing SpriteSpin is a bit weird, because you must ensure that jQuery is available. Here is an example that works on stackblitz
https://stackblitz.com/edit/spritespin-typescript?file=index.ts

The next release of spritespin has no dependencies at all and the library can be imported without hassle in modern workflows
https://stackblitz.com/edit/spritespin5-typescript?file=index.ts

There is also a beta website in case you are interested in the next release
https://spritespin-beta.ginie.eu/
